#!/usr/bin/env node

const program = require('commander')
const updateNotifier = require('update-notifier')
const pkg = require('./package.json')

program
  .version('1.0.0')
  .description('Losant CLI is a command line tool to aid developers while creating custom application on top of the Losant Platform')
  .command('configure', 'Configure the command line tool')
  .command('views', 'Manage Experience Views')
  .parse(process.argv);

const notifier = updateNotifier({ pkg });
notifier.notify();