#!/usr/bin/env node

const program = require('commander')
const c = require('chalk')
const { saveConfig } = require('./lib/utils')
const inquirer = require('inquirer')
const log = console.log

program
  .description('Configure the command line tool')
  .option('-a, --app <id>', 'set the application id')
  .option('-t, --token <token>', 'set the api token')
  .option('-c, --config <file>', 'config file to run the command with. (default: "losant.yml")')
  .option('-d, --dir <dir>', 'directory to run the command in. (default: current directory)')
  .parse(process.argv)

if (!program.app) {
  log(`${c.red('error')} application id is required`)
  process.exit(1)
}
if (!program.token) {
  log(`${c.red('error')} api token is required`)
  process.exit(1)
}

try {
  if (program.dir) {
    process.chdir(program.dir)
  }
  const config = { applicationId: program.app, apiToken: program.token }
  const file = saveConfig(program.config, config)
  log(`${c.green('success')} configuration written to ${c.bold(file)}`)
} catch (e) {
  log(`${c.red('error')} failed to write configuration: ${c.bold(e.message)}`)
}